/**
 * Endpoint discovery: parse every GET endpoint out of Fleet's rest-api.md,
 * auto-derive path-parameter chaining, apply manual OVERRIDES, and write the
 * result to probes.generated.ts (committed, so the list is reviewable in PRs).
 *
 *   npm run discover
 *
 * Only the docs are read here — no live API, no token. The chaining heuristic:
 * a path param `{p}` is sourced from the collection ending just before its
 * segment, picking `<lastSegment>.*.<field>`. Endpoints whose params can't be
 * resolved this way are left out — add them via an OVERRIDE in probes.ts.
 */
import * as fs from 'fs';
import * as path from 'path';
import { fetchDocs, discoverEndpoints } from './docs';
import { OVERRIDES, type Probe } from './probes';

const OUT = path.join(__dirname, 'probes.generated.ts');

function slug(specPath: string): string {
  return specPath
    .replace('/api/v1/fleet/', '')
    .replace(/\{(\w+)\}/g, 'by-$1')
    .replace(/\//g, '-');
}

function lastSegment(p: string): string {
  const parts = p.split('/').filter(Boolean);
  return parts[parts.length - 1];
}

/** Resolve each `{param}` to a chaining source, or report the path as unresolvable. */
function autoChain(
  specPath: string,
  getPaths: Set<string>,
): { params?: Record<string, { from: string; pick: string }>; resolved: boolean } {
  const segments = specPath.split('/');
  const params: Record<string, { from: string; pick: string }> = {};
  let resolved = true;
  segments.forEach((seg, i) => {
    const pm = seg.match(/^\{(\w+)\}$/);
    if (!pm) return;
    const name = pm[1];
    const source = segments.slice(0, i).join('/');
    if (!getPaths.has(source)) {
      resolved = false;
      return;
    }
    params[name] = { from: slug(source), pick: `${lastSegment(source)}.*.${name === 'id' ? 'id' : name}` };
  });
  return { params: Object.keys(params).length ? params : undefined, resolved };
}

async function main(): Promise<void> {
  const md = await fetchDocs();
  const endpoints = discoverEndpoints(md).filter((e) => e.method === 'GET');
  const getPaths = new Set(endpoints.map((e) => e.path));

  const probes = new Map<string, Probe>();
  let skippedUnresolved = 0;
  for (const ep of endpoints) {
    const { params, resolved } = autoChain(ep.path, getPaths);
    if (!resolved) {
      skippedUnresolved++;
      continue;
    }
    probes.set(ep.path, {
      name: slug(ep.path),
      method: 'get',
      specPath: ep.path,
      summary: ep.summary,
      tags: ep.tags,
      ...(params ? { params } : {}),
    });
  }

  // Apply overrides: drop, merge, or add.
  for (const ov of OVERRIDES) {
    const { skip, ...fields } = ov;
    if (skip) {
      probes.delete(ov.specPath);
      continue;
    }
    const existing = probes.get(ov.specPath);
    probes.set(ov.specPath, existing ? { ...existing, ...fields } : (fields as Probe));
  }

  const list = [...probes.values()].sort((a, b) => a.specPath.localeCompare(b.specPath));
  const header =
    `// AUTO-GENERATED by \`npm run discover\` from Fleet's rest-api.md. Do not edit by hand.\n` +
    `// Manual fixes live in probes.ts (OVERRIDES). ${list.length} probe(s).\n\n`;
  fs.writeFileSync(OUT, `${header}import type { Probe } from './probes';\n\nexport const PROBES: Probe[] = ${JSON.stringify(list, null, 2)};\n`);

  console.log(`Discovered ${endpoints.length} GET endpoint(s); ${skippedUnresolved} skipped (unresolvable params).`);
  console.log(`Wrote ${list.length} probe(s) to ${path.basename(OUT)}.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
