// AUTO-GENERATED by `npm run discover` from Fleet's rest-api.md. Do not edit by hand.
// Manual fixes live in probes.ts (OVERRIDES). 117 probe(s).

import type { Probe } from './probes';

export const PROBES: Probe[] = [
  {
    "name": "ab_tokens",
    "method": "get",
    "specPath": "/api/v1/fleet/ab_tokens",
    "summary": "List Apple Business (AB) tokens",
    "tags": [
      "Integrations"
    ]
  },
  {
    "name": "activities",
    "method": "get",
    "specPath": "/api/v1/fleet/activities",
    "summary": "List activities",
    "tags": [
      "Activities"
    ]
  },
  {
    "name": "android_enterprise",
    "method": "get",
    "specPath": "/api/v1/fleet/android_enterprise",
    "summary": "Get Android Enterprise",
    "tags": [
      "Integrations"
    ]
  },
  {
    "name": "apns",
    "method": "get",
    "specPath": "/api/v1/fleet/apns",
    "summary": "Get Apple Push Notification service (APNs)",
    "tags": [
      "Integrations"
    ]
  },
  {
    "name": "bootstrap",
    "method": "get",
    "specPath": "/api/v1/fleet/bootstrap",
    "summary": "Download bootstrap package",
    "tags": [
      "Setup experience"
    ]
  },
  {
    "name": "bootstrap-by-fleet_id-metadata",
    "method": "get",
    "specPath": "/api/v1/fleet/bootstrap/{fleet_id}/metadata",
    "summary": "Get bootstrap package metadata",
    "tags": [
      "Setup experience"
    ],
    "params": {
      "fleet_id": {
        "from": "bootstrap",
        "pick": "bootstrap.*.fleet_id"
      }
    }
  },
  {
    "name": "bootstrap-summary",
    "method": "get",
    "specPath": "/api/v1/fleet/bootstrap/summary",
    "summary": "Get bootstrap package status",
    "tags": [
      "Setup experience"
    ]
  },
  {
    "name": "carves",
    "method": "get",
    "specPath": "/api/v1/fleet/carves",
    "summary": "List carves",
    "tags": [
      "File carving"
    ]
  },
  {
    "name": "carves-by-id",
    "method": "get",
    "specPath": "/api/v1/fleet/carves/{id}",
    "summary": "Get carve",
    "tags": [
      "File carving"
    ],
    "params": {
      "id": {
        "from": "carves",
        "pick": "carves.*.id"
      }
    }
  },
  {
    "name": "certificate_authorities",
    "method": "get",
    "specPath": "/api/v1/fleet/certificate_authorities",
    "summary": "List certificate authorities (CAs)",
    "tags": [
      "Certificates"
    ]
  },
  {
    "name": "certificate_authorities-by-id",
    "method": "get",
    "specPath": "/api/v1/fleet/certificate_authorities/{id}",
    "summary": "Get certificate authority (CA)",
    "tags": [
      "Certificates"
    ],
    "params": {
      "id": {
        "from": "certificate_authorities",
        "pick": "certificate_authorities.*.id"
      }
    }
  },
  {
    "name": "certificates",
    "method": "get",
    "specPath": "/api/v1/fleet/certificates",
    "summary": "List certificate templates",
    "tags": [
      "Certificates"
    ]
  },
  {
    "name": "certificates-by-id",
    "method": "get",
    "specPath": "/api/v1/fleet/certificates/{id}",
    "summary": "Get certificate template",
    "tags": [
      "Certificates"
    ],
    "params": {
      "id": {
        "from": "certificates",
        "pick": "certificates.*.id"
      }
    }
  },
  {
    "name": "commands",
    "method": "get",
    "specPath": "/api/v1/fleet/commands",
    "summary": "List MDM commands",
    "tags": [
      "Commands"
    ]
  },
  {
    "name": "commands-results",
    "method": "get",
    "specPath": "/api/v1/fleet/commands/results",
    "summary": "Get MDM command results",
    "tags": [
      "Commands"
    ]
  },
  {
    "name": "conditional_access-idp-apple-profile",
    "method": "get",
    "specPath": "/api/v1/fleet/conditional_access/idp/apple/profile",
    "summary": "Get Okta configuration profile",
    "tags": [
      "Conditional access"
    ]
  },
  {
    "name": "conditional_access-idp-signing_cert",
    "method": "get",
    "specPath": "/api/v1/fleet/conditional_access/idp/signing_cert",
    "summary": "Get Okta certificate",
    "tags": [
      "Conditional access"
    ]
  },
  {
    "name": "config",
    "method": "get",
    "specPath": "/api/v1/fleet/config",
    "summary": "Get configuration",
    "tags": [
      "Fleet configuration"
    ]
  },
  {
    "name": "config-certificate",
    "method": "get",
    "specPath": "/api/v1/fleet/config/certificate",
    "summary": "Get Fleet certificate",
    "tags": [
      "Fleet configuration"
    ]
  },
  {
    "name": "configuration_profiles",
    "method": "get",
    "specPath": "/api/v1/fleet/configuration_profiles",
    "summary": "List configuration profiles",
    "tags": [
      "OS settings"
    ]
  },
  {
    "name": "configuration_profiles-by-profile_uuid",
    "method": "get",
    "specPath": "/api/v1/fleet/configuration_profiles/{profile_uuid}",
    "summary": "Get or download configuration profile",
    "tags": [
      "OS settings"
    ],
    "params": {
      "profile_uuid": {
        "from": "configuration_profiles",
        "pick": "configuration_profiles.*.profile_uuid"
      }
    }
  },
  {
    "name": "configuration_profiles-by-profile_uuid-status",
    "method": "get",
    "specPath": "/api/v1/fleet/configuration_profiles/{profile_uuid}/status",
    "summary": "Get OS setting (configuration profile) status",
    "tags": [
      "OS settings"
    ],
    "params": {
      "profile_uuid": {
        "from": "configuration_profiles",
        "pick": "configuration_profiles.*.profile_uuid"
      }
    }
  },
  {
    "name": "configuration_profiles-f663713f-04ee-40f0-a95a-7af428c351a9",
    "method": "get",
    "specPath": "/api/v1/fleet/configuration_profiles/f663713f-04ee-40f0-a95a-7af428c351a9",
    "summary": "Get or download configuration profile",
    "tags": [
      "OS settings"
    ]
  },
  {
    "name": "configuration_profiles-f663713f-04ee-40f0-a95a-7af428c351a9-status",
    "method": "get",
    "specPath": "/api/v1/fleet/configuration_profiles/f663713f-04ee-40f0-a95a-7af428c351a9/status",
    "summary": "Get OS setting (configuration profile) status",
    "tags": [
      "OS settings"
    ]
  },
  {
    "name": "configuration_profiles-summary",
    "method": "get",
    "specPath": "/api/v1/fleet/configuration_profiles/summary",
    "summary": "Get OS settings (configuration profiles) status",
    "tags": [
      "OS settings"
    ]
  },
  {
    "name": "custom_variables",
    "method": "get",
    "specPath": "/api/v1/fleet/custom_variables",
    "summary": "List custom variables",
    "tags": [
      "Custom variables"
    ]
  },
  {
    "name": "device-abcdef012456789",
    "method": "get",
    "specPath": "/api/v1/fleet/device/abcdef012456789",
    "summary": "Get host by Fleet Desktop token",
    "tags": [
      "Hosts"
    ]
  },
  {
    "name": "disk_encryption",
    "method": "get",
    "specPath": "/api/v1/fleet/disk_encryption",
    "summary": "Get disk encryption status",
    "tags": [
      "OS settings"
    ]
  },
  {
    "name": "enrollment_profiles-automatic",
    "method": "get",
    "specPath": "/api/v1/fleet/enrollment_profiles/automatic",
    "summary": "Get custom MDM setup enrollment profile",
    "tags": [
      "Setup experience"
    ]
  },
  {
    "name": "enrollment_profiles-automatic-default",
    "method": "get",
    "specPath": "/api/v1/fleet/enrollment_profiles/automatic/default",
    "summary": "Get Fleet default MDM setup enrollment profile",
    "tags": [
      "Setup experience"
    ]
  },
  {
    "name": "enrollment_profiles-manual",
    "method": "get",
    "specPath": "/api/v1/fleet/enrollment_profiles/manual",
    "summary": "Get manual enrollment profile",
    "tags": [
      "Setup experience"
    ]
  },
  {
    "name": "enrollment_profiles-ota",
    "method": "get",
    "specPath": "/api/v1/fleet/enrollment_profiles/ota",
    "summary": "Get Over-the-Air (OTA) enrollment profile",
    "tags": [
      "Setup experience"
    ]
  },
  {
    "name": "fleets",
    "method": "get",
    "specPath": "/api/v1/fleet/fleets",
    "summary": "List fleets",
    "tags": [
      "Fleets"
    ]
  },
  {
    "name": "fleets-by-fleet_id-policies-count",
    "method": "get",
    "specPath": "/api/v1/fleet/fleets/{fleet_id}/policies/count",
    "summary": "Get fleet-level policies count",
    "tags": [
      "Policies"
    ],
    "params": {
      "fleet_id": {
        "from": "fleets",
        "pick": "fleets.*.fleet_id"
      }
    }
  },
  {
    "name": "fleets-by-id",
    "method": "get",
    "specPath": "/api/v1/fleet/fleets/{id}",
    "summary": "Get fleet",
    "tags": [
      "Fleets"
    ],
    "params": {
      "id": {
        "from": "fleets",
        "pick": "fleets.*.id"
      }
    }
  },
  {
    "name": "fleets-by-id-policies",
    "method": "get",
    "specPath": "/api/v1/fleet/fleets/{id}/policies",
    "summary": "List fleet-level policies",
    "tags": [
      "Policies"
    ],
    "params": {
      "id": {
        "from": "fleets",
        "pick": "fleets.*.id"
      }
    }
  },
  {
    "name": "fleets-by-id-secrets",
    "method": "get",
    "specPath": "/api/v1/fleet/fleets/{id}/secrets",
    "summary": "Get fleet-level enroll secrets",
    "tags": [
      "Fleet configuration"
    ],
    "params": {
      "id": {
        "from": "fleets",
        "pick": "fleets.*.id"
      }
    }
  },
  {
    "name": "global-policies",
    "method": "get",
    "specPath": "/api/v1/fleet/global/policies",
    "summary": "List policies",
    "tags": [
      "Policies"
    ]
  },
  {
    "name": "global-policies-by-id",
    "method": "get",
    "specPath": "/api/v1/fleet/global/policies/{id}",
    "summary": "Get policy",
    "tags": [
      "Policies"
    ],
    "params": {
      "id": {
        "from": "global-policies",
        "pick": "policies.*.id"
      }
    }
  },
  {
    "name": "host_summary",
    "method": "get",
    "specPath": "/api/v1/fleet/host_summary",
    "summary": "Get hosts summary",
    "tags": [
      "Hosts"
    ]
  },
  {
    "name": "hosts",
    "method": "get",
    "specPath": "/api/v1/fleet/hosts",
    "summary": "List hosts",
    "tags": [
      "Hosts"
    ],
    "query": {
      "per_page": 100
    }
  },
  {
    "name": "hosts-by-id",
    "method": "get",
    "specPath": "/api/v1/fleet/hosts/{id}",
    "summary": "Get host",
    "tags": [
      "Hosts"
    ],
    "params": {
      "id": {
        "from": "hosts",
        "pick": "hosts.*.id"
      }
    }
  },
  {
    "name": "hosts-by-id-activities",
    "method": "get",
    "specPath": "/api/v1/fleet/hosts/{id}/activities",
    "summary": "Get host's past activity",
    "tags": [
      "Hosts"
    ],
    "params": {
      "id": {
        "from": "hosts",
        "pick": "hosts.*.id"
      }
    },
    "query": {
      "per_page": 100
    }
  },
  {
    "name": "hosts-by-id-activities-upcoming",
    "method": "get",
    "specPath": "/api/v1/fleet/hosts/{id}/activities/upcoming",
    "summary": "Get host's upcoming activity",
    "tags": [
      "Hosts"
    ],
    "params": {
      "id": {
        "from": "hosts",
        "pick": "hosts.*.id"
      }
    }
  },
  {
    "name": "hosts-by-id-certificates",
    "method": "get",
    "specPath": "/api/v1/fleet/hosts/{id}/certificates",
    "summary": "Get host's certificates",
    "tags": [
      "Hosts"
    ],
    "params": {
      "id": {
        "from": "hosts",
        "pick": "hosts.*.id"
      }
    }
  },
  {
    "name": "hosts-by-id-configuration_profiles",
    "method": "get",
    "specPath": "/api/v1/fleet/hosts/{id}/configuration_profiles",
    "summary": "Get host's OS settings (configuration profile)",
    "tags": [
      "Hosts"
    ],
    "params": {
      "id": {
        "from": "hosts",
        "pick": "hosts.*.id"
      }
    }
  },
  {
    "name": "hosts-by-id-device_url",
    "method": "get",
    "specPath": "/api/v1/fleet/hosts/{id}/device_url",
    "summary": "Get host's device page URL",
    "tags": [
      "Hosts"
    ],
    "params": {
      "id": {
        "from": "hosts",
        "pick": "hosts.*.id"
      }
    }
  },
  {
    "name": "hosts-by-id-encryption_key",
    "method": "get",
    "specPath": "/api/v1/fleet/hosts/{id}/encryption_key",
    "summary": "Get host's disk encryption key",
    "tags": [
      "Hosts"
    ],
    "params": {
      "id": {
        "from": "hosts",
        "pick": "hosts.*.id"
      }
    }
  },
  {
    "name": "hosts-by-id-health",
    "method": "get",
    "specPath": "/api/v1/fleet/hosts/{id}/health",
    "summary": "Get host's device health report",
    "tags": [
      "Hosts"
    ],
    "params": {
      "id": {
        "from": "hosts",
        "pick": "hosts.*.id"
      }
    }
  },
  {
    "name": "hosts-by-id-macadmins",
    "method": "get",
    "specPath": "/api/v1/fleet/hosts/{id}/macadmins",
    "summary": "Get host's mobile device management (MDM) and Munki information",
    "tags": [
      "Hosts"
    ],
    "params": {
      "id": {
        "from": "hosts",
        "pick": "hosts.*.id"
      }
    }
  },
  {
    "name": "hosts-by-id-managed_account_password",
    "method": "get",
    "specPath": "/api/v1/fleet/hosts/{id}/managed_account_password",
    "summary": "Get host's managed account password",
    "tags": [
      "Hosts"
    ],
    "params": {
      "id": {
        "from": "hosts",
        "pick": "hosts.*.id"
      }
    }
  },
  {
    "name": "hosts-by-id-mdm",
    "method": "get",
    "specPath": "/api/v1/fleet/hosts/{id}/mdm",
    "summary": "Get host's mobile device management (MDM) information",
    "tags": [
      "Hosts"
    ],
    "params": {
      "id": {
        "from": "hosts",
        "pick": "hosts.*.id"
      }
    }
  },
  {
    "name": "hosts-by-id-recovery_lock_password",
    "method": "get",
    "specPath": "/api/v1/fleet/hosts/{id}/recovery_lock_password",
    "summary": "Get host's Recovery Lock password",
    "tags": [
      "Hosts"
    ],
    "params": {
      "id": {
        "from": "hosts",
        "pick": "hosts.*.id"
      }
    }
  },
  {
    "name": "hosts-by-id-reports",
    "method": "get",
    "specPath": "/api/v1/fleet/hosts/{id}/reports",
    "summary": "List host's reports",
    "tags": [
      "Reports"
    ],
    "params": {
      "id": {
        "from": "hosts",
        "pick": "hosts.*.id"
      }
    }
  },
  {
    "name": "hosts-by-id-reports-by-report_id",
    "method": "get",
    "specPath": "/api/v1/fleet/hosts/{id}/reports/{report_id}",
    "summary": "Get host's report data",
    "tags": [
      "Reports"
    ],
    "params": {
      "id": {
        "from": "hosts",
        "pick": "hosts.*.id"
      },
      "report_id": {
        "from": "hosts-by-id-reports",
        "pick": "reports.*.report_id"
      }
    }
  },
  {
    "name": "hosts-by-id-scripts",
    "method": "get",
    "specPath": "/api/v1/fleet/hosts/{id}/scripts",
    "summary": "List host's scripts",
    "tags": [
      "Scripts"
    ],
    "params": {
      "id": {
        "from": "hosts",
        "pick": "hosts.*.id"
      }
    }
  },
  {
    "name": "hosts-by-id-software",
    "method": "get",
    "specPath": "/api/v1/fleet/hosts/{id}/software",
    "summary": "Get host's software",
    "tags": [
      "Hosts"
    ],
    "params": {
      "id": {
        "from": "hosts",
        "pick": "hosts.*.id"
      }
    },
    "query": {
      "per_page": 100
    }
  },
  {
    "name": "hosts-count",
    "method": "get",
    "specPath": "/api/v1/fleet/hosts/count",
    "summary": "Count hosts",
    "tags": [
      "Hosts"
    ]
  },
  {
    "name": "hosts-identifier-by-identifier",
    "method": "get",
    "specPath": "/api/v1/fleet/hosts/identifier/{identifier}",
    "summary": "Get host by identifier",
    "tags": [
      "Hosts"
    ],
    "responseName": "HostsByIdResponse",
    "params": {
      "identifier": {
        "from": "hosts",
        "pick": "hosts.*.uuid"
      }
    }
  },
  {
    "name": "hosts-identifier-392547dc-0000-0000-a87a-d701ff75bc65",
    "method": "get",
    "specPath": "/api/v1/fleet/hosts/identifier/392547dc-0000-0000-a87a-d701ff75bc65",
    "summary": "Get host by identifier",
    "tags": [
      "Hosts"
    ]
  },
  {
    "name": "hosts-report",
    "method": "get",
    "specPath": "/api/v1/fleet/hosts/report",
    "summary": "Get hosts report in CSV",
    "tags": [
      "Hosts"
    ]
  },
  {
    "name": "hosts-summary-mdm",
    "method": "get",
    "specPath": "/api/v1/fleet/hosts/summary/mdm",
    "summary": "Get mobile device management (MDM) status",
    "tags": [
      "Hosts"
    ]
  },
  {
    "name": "invites",
    "method": "get",
    "specPath": "/api/v1/fleet/invites",
    "summary": "List invites",
    "tags": [
      "Users"
    ]
  },
  {
    "name": "invites-by-token",
    "method": "get",
    "specPath": "/api/v1/fleet/invites/{token}",
    "summary": "Verify invite",
    "tags": [
      "Users"
    ],
    "params": {
      "token": {
        "from": "invites",
        "pick": "invites.*.token"
      }
    }
  },
  {
    "name": "invites-abcdef012456789",
    "method": "get",
    "specPath": "/api/v1/fleet/invites/abcdef012456789",
    "summary": "Verify invite",
    "tags": [
      "Users"
    ]
  },
  {
    "name": "labels",
    "method": "get",
    "specPath": "/api/v1/fleet/labels",
    "summary": "List labels",
    "tags": [
      "Labels"
    ]
  },
  {
    "name": "labels-by-id",
    "method": "get",
    "specPath": "/api/v1/fleet/labels/{id}",
    "summary": "Get label",
    "tags": [
      "Labels"
    ],
    "params": {
      "id": {
        "from": "labels",
        "pick": "labels.*.id"
      }
    }
  },
  {
    "name": "labels-by-id-hosts",
    "method": "get",
    "specPath": "/api/v1/fleet/labels/{id}/hosts",
    "summary": "List label's hosts",
    "tags": [
      "Labels"
    ],
    "params": {
      "id": {
        "from": "labels",
        "pick": "labels.*.id"
      }
    }
  },
  {
    "name": "labels-summary",
    "method": "get",
    "specPath": "/api/v1/fleet/labels/summary",
    "summary": "Get labels summary",
    "tags": [
      "Labels"
    ]
  },
  {
    "name": "macadmins",
    "method": "get",
    "specPath": "/api/v1/fleet/macadmins",
    "summary": "Get hosts' aggregate mobile device management (MDM) and Munki information",
    "tags": [
      "Hosts"
    ]
  },
  {
    "name": "mdm-apple-commandresults",
    "method": "get",
    "specPath": "/api/v1/fleet/mdm/apple/commandresults",
    "summary": "Get MDM command results",
    "tags": [
      "Commands"
    ]
  },
  {
    "name": "mdm-apple-commands",
    "method": "get",
    "specPath": "/api/v1/fleet/mdm/apple/commands",
    "summary": "List MDM commands",
    "tags": [
      "Commands"
    ]
  },
  {
    "name": "mdm-apple-profiles",
    "method": "get",
    "specPath": "/api/v1/fleet/mdm/apple/profiles",
    "summary": "List configuration profiles",
    "tags": [
      "OS settings"
    ]
  },
  {
    "name": "mdm-apple-profiles-by-profile_id",
    "method": "get",
    "specPath": "/api/v1/fleet/mdm/apple/profiles/{profile_id}",
    "summary": "Get or download configuration profile",
    "tags": [
      "OS settings"
    ],
    "params": {
      "profile_id": {
        "from": "mdm-apple-profiles",
        "pick": "profiles.*.profile_id"
      }
    }
  },
  {
    "name": "mdm-apple-profiles-summary",
    "method": "get",
    "specPath": "/api/v1/fleet/mdm/apple/profiles/summary",
    "summary": "Get OS settings (configuration profiles) status",
    "tags": [
      "OS settings"
    ]
  },
  {
    "name": "me",
    "method": "get",
    "specPath": "/api/v1/fleet/me",
    "summary": "Me",
    "tags": [
      "Authentication"
    ]
  },
  {
    "name": "os_versions",
    "method": "get",
    "specPath": "/api/v1/fleet/os_versions",
    "summary": "List operating systems",
    "tags": [
      "Software"
    ]
  },
  {
    "name": "os_versions-by-id",
    "method": "get",
    "specPath": "/api/v1/fleet/os_versions/{id}",
    "summary": "Get operating system version",
    "tags": [
      "Software"
    ],
    "params": {
      "id": {
        "from": "os_versions",
        "pick": "os_versions.*.id"
      }
    }
  },
  {
    "name": "policies-count",
    "method": "get",
    "specPath": "/api/v1/fleet/policies/count",
    "summary": "Get policies count",
    "tags": [
      "Policies"
    ]
  },
  {
    "name": "queries-run",
    "method": "get",
    "specPath": "/api/v1/fleet/queries/run",
    "summary": "Run live report",
    "tags": [
      "Reports"
    ]
  },
  {
    "name": "reports",
    "method": "get",
    "specPath": "/api/v1/fleet/reports",
    "summary": "List reports",
    "tags": [
      "Reports"
    ]
  },
  {
    "name": "reports-by-id",
    "method": "get",
    "specPath": "/api/v1/fleet/reports/{id}",
    "summary": "Get report",
    "tags": [
      "Reports"
    ],
    "params": {
      "id": {
        "from": "reports",
        "pick": "reports.*.id"
      }
    }
  },
  {
    "name": "reports-by-id-report",
    "method": "get",
    "specPath": "/api/v1/fleet/reports/{id}/report",
    "summary": "Get report data",
    "tags": [
      "Reports"
    ],
    "params": {
      "id": {
        "from": "reports",
        "pick": "reports.*.id"
      }
    }
  },
  {
    "name": "rest_api",
    "method": "get",
    "specPath": "/api/v1/fleet/rest_api",
    "summary": "List API endpoints for API-only user permissions",
    "tags": [
      "Users"
    ]
  },
  {
    "name": "scim-details",
    "method": "get",
    "specPath": "/api/v1/fleet/scim/details",
    "summary": "Get identity provider (IdP) details",
    "tags": [
      "Integrations"
    ]
  },
  {
    "name": "scripts",
    "method": "get",
    "specPath": "/api/v1/fleet/scripts",
    "summary": "List scripts",
    "tags": [
      "Scripts"
    ]
  },
  {
    "name": "scripts-by-id",
    "method": "get",
    "specPath": "/api/v1/fleet/scripts/{id}",
    "summary": "Get or download script",
    "tags": [
      "Scripts"
    ],
    "params": {
      "id": {
        "from": "scripts",
        "pick": "scripts.*.id"
      }
    }
  },
  {
    "name": "scripts-batch",
    "method": "get",
    "specPath": "/api/v1/fleet/scripts/batch",
    "summary": "List batch scripts",
    "tags": [
      "Scripts"
    ]
  },
  {
    "name": "scripts-batch-by-batch_execution_id",
    "method": "get",
    "specPath": "/api/v1/fleet/scripts/batch/{batch_execution_id}",
    "summary": "Get batch script",
    "tags": [
      "Scripts"
    ],
    "params": {
      "batch_execution_id": {
        "from": "scripts-batch",
        "pick": "batch.*.batch_execution_id"
      }
    }
  },
  {
    "name": "scripts-batch-by-batch_execution_id-host_results",
    "method": "get",
    "specPath": "/api/v1/fleet/scripts/batch/{batch_execution_id}/host_results",
    "summary": "List hosts targeted in batch script",
    "tags": [
      "Scripts"
    ],
    "params": {
      "batch_execution_id": {
        "from": "scripts-batch",
        "pick": "batch.*.batch_execution_id"
      }
    }
  },
  {
    "name": "scripts-batch-abc-def",
    "method": "get",
    "specPath": "/api/v1/fleet/scripts/batch/abc-def",
    "summary": "Get batch script",
    "tags": [
      "Scripts"
    ]
  },
  {
    "name": "scripts-batch-abc-def-host-results",
    "method": "get",
    "specPath": "/api/v1/fleet/scripts/batch/abc-def/host-results",
    "summary": "List hosts targeted in batch script",
    "tags": [
      "Scripts"
    ]
  },
  {
    "name": "setup_experience-eula-AA598E2A-7952-46E3-B89D-526D45F7E233",
    "method": "get",
    "specPath": "/api/v1/fleet/setup_experience/eula/AA598E2A-7952-46E3-B89D-526D45F7E233",
    "summary": "Download EULA",
    "tags": [
      "Setup experience"
    ]
  },
  {
    "name": "setup_experience-eula-metadata",
    "method": "get",
    "specPath": "/api/v1/fleet/setup_experience/eula/metadata",
    "summary": "Get EULA metadata",
    "tags": [
      "Setup experience"
    ]
  },
  {
    "name": "setup_experience-script",
    "method": "get",
    "specPath": "/api/v1/fleet/setup_experience/script",
    "summary": "Get or download setup experience script",
    "tags": [
      "Setup experience"
    ]
  },
  {
    "name": "setup_experience-software",
    "method": "get",
    "specPath": "/api/v1/fleet/setup_experience/software",
    "summary": "List setup experience software",
    "tags": [
      "Setup experience"
    ]
  },
  {
    "name": "software-app_store_apps",
    "method": "get",
    "specPath": "/api/v1/fleet/software/app_store_apps",
    "summary": "List Apple App Store apps",
    "tags": [
      "Software"
    ]
  },
  {
    "name": "software-fleet_maintained_apps",
    "method": "get",
    "specPath": "/api/v1/fleet/software/fleet_maintained_apps",
    "summary": "List Fleet-maintained apps",
    "tags": [
      "Software"
    ]
  },
  {
    "name": "software-fleet_maintained_apps-by-id",
    "method": "get",
    "specPath": "/api/v1/fleet/software/fleet_maintained_apps/{id}",
    "summary": "Get Fleet-maintained app",
    "tags": [
      "Software"
    ],
    "params": {
      "id": {
        "from": "software-fleet_maintained_apps",
        "pick": "fleet_maintained_apps.*.id"
      }
    }
  },
  {
    "name": "software-install-b15ce221-e22e-4c6a-afe7-5b3400a017da-results",
    "method": "get",
    "specPath": "/api/v1/fleet/software/install/b15ce221-e22e-4c6a-afe7-5b3400a017da/results",
    "summary": "Get software install result",
    "tags": [
      "Software"
    ]
  },
  {
    "name": "software-self_service_categories",
    "method": "get",
    "specPath": "/api/v1/fleet/software/self_service_categories",
    "summary": "List self-service categories",
    "tags": [
      "Self-service categories"
    ]
  },
  {
    "name": "software-titles",
    "method": "get",
    "specPath": "/api/v1/fleet/software/titles",
    "summary": "List software",
    "tags": [
      "Software"
    ]
  },
  {
    "name": "software-titles-by-id",
    "method": "get",
    "specPath": "/api/v1/fleet/software/titles/{id}",
    "summary": "Get software",
    "tags": [
      "Software"
    ],
    "params": {
      "id": {
        "from": "software-titles",
        "pick": "software_titles.*.id"
      }
    }
  },
  {
    "name": "software-titles-by-id-icon",
    "method": "get",
    "specPath": "/api/v1/fleet/software/titles/{id}/icon",
    "summary": "Download software icon",
    "tags": [
      "Software"
    ],
    "params": {
      "id": {
        "from": "software-titles",
        "pick": "software_titles.*.id"
      }
    }
  },
  {
    "name": "software-titles-by-id-package",
    "method": "get",
    "specPath": "/api/v1/fleet/software/titles/{id}/package",
    "summary": "Download software",
    "tags": [
      "Software"
    ],
    "params": {
      "id": {
        "from": "software-titles",
        "pick": "software_titles.*.id"
      }
    }
  },
  {
    "name": "software-versions",
    "method": "get",
    "specPath": "/api/v1/fleet/software/versions",
    "summary": "List software versions",
    "tags": [
      "Software"
    ]
  },
  {
    "name": "software-versions-by-id",
    "method": "get",
    "specPath": "/api/v1/fleet/software/versions/{id}",
    "summary": "Get software version",
    "tags": [
      "Software"
    ],
    "params": {
      "id": {
        "from": "software-versions",
        "pick": "software.*.id"
      }
    }
  },
  {
    "name": "spec-enroll_secret",
    "method": "get",
    "specPath": "/api/v1/fleet/spec/enroll_secret",
    "summary": "Get global enroll secrets",
    "tags": [
      "Fleet configuration"
    ]
  },
  {
    "name": "sso",
    "method": "get",
    "specPath": "/api/v1/fleet/sso",
    "summary": "SSO config",
    "tags": [
      "Authentication"
    ]
  },
  {
    "name": "users",
    "method": "get",
    "specPath": "/api/v1/fleet/users",
    "summary": "List users",
    "tags": [
      "Users"
    ]
  },
  {
    "name": "users-by-id",
    "method": "get",
    "specPath": "/api/v1/fleet/users/{id}",
    "summary": "Get user",
    "tags": [
      "Users"
    ],
    "params": {
      "id": {
        "from": "users",
        "pick": "users.*.id"
      }
    }
  },
  {
    "name": "users-by-id-sessions",
    "method": "get",
    "specPath": "/api/v1/fleet/users/{id}/sessions",
    "summary": "List sessions",
    "tags": [
      "Users"
    ],
    "params": {
      "id": {
        "from": "users",
        "pick": "users.*.id"
      }
    }
  },
  {
    "name": "version",
    "method": "get",
    "specPath": "/api/v1/fleet/version",
    "summary": "Get version",
    "tags": [
      "Fleet configuration"
    ]
  },
  {
    "name": "vpp_tokens",
    "method": "get",
    "specPath": "/api/v1/fleet/vpp_tokens",
    "summary": "List Volume Purchasing Program (VPP) tokens",
    "tags": [
      "Integrations"
    ]
  },
  {
    "name": "vulnerabilities",
    "method": "get",
    "specPath": "/api/v1/fleet/vulnerabilities",
    "summary": "List vulnerabilities",
    "tags": [
      "Vulnerabilities"
    ]
  },
  {
    "name": "vulnerabilities-by-cve",
    "method": "get",
    "specPath": "/api/v1/fleet/vulnerabilities/{cve}",
    "summary": "Get vulnerability",
    "tags": [
      "Vulnerabilities"
    ],
    "params": {
      "cve": {
        "from": "vulnerabilities",
        "pick": "vulnerabilities.*.cve"
      }
    }
  },
  {
    "name": "vulnerabilities-cve-2022-30190",
    "method": "get",
    "specPath": "/api/v1/fleet/vulnerabilities/cve-2022-30190",
    "summary": "Get vulnerability",
    "tags": [
      "Vulnerabilities"
    ]
  }
];
